---
- name: Import WordPress secret variable file
  include_vars: "main.yml"
  no_log: true

- name: Get WordPress
  repo: 'https://github.com/bukka/WordPress.git'
  dest: /var/www/wordpress/
  version: bk

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/var/www/wordpress/

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/wordpress/

- name: Change ownership of WordPress installation
  file: path=/var/www/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes setype=httpd_sys_content_t
  sudo: True

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
